### ISSUE TITLE
Documentation should include prerequisites required?  X should be optional...

### ISSUE THREAD

**Issue by furicle** [klazarsk/storagetoolkit#2]
Minor issue - `resize` is not installed on the first system I tried this on, resulting in `./topdiskconsumer: line 134: resize: command not found`

Using yum whatprovides I see that's part of XTerm?   Headless systems like mine won't have that.

If that output is optional (and it seems to be) perhaps just changing line 134 to
`command -v resize >/dev/null 2>&1`  will tidy up the output.

**Comment by klazarsk** [comment]
headless systems very often have xterm installed for shooting a client window to a workstation, but point taken.

**Comment by klazarsk** [comment]
I had actually handled this but along the way the redirect to null on the resize command got reversed and never caught it because I have xterm installed on my systems. Apologies for not catching this!
