### ISSUE TITLE
mtime is dangerous

### ISSUE THREAD

**Issue by adRn-s** [klazarsk/storagetoolkit#4]
hi, I recently wrote a script to do similar task. Fyi, if anyone downloads a file from a webserver it will get the file attributes from it, and find's mtime argument will detect it as old even though it's a recent download. You may prefer to use `ctime` :)

**Comment by klazarsk** [comment]
ctime is more dangerous because it may rule out files that have aged, simply because someone did a recursive chmod, chown, etc. so the choice to go with mtime was deliberate.
